#!/usr/bin/env python3

import subprocess
import sys

maxsize=10000
NULLSHA='0000000000000000000000000000000000000000'

def call(cmd):
    output = subprocess.check_output(cmd)
    return output.decode('UTF8')

def getRef(line):
    s = line.split()
    if len(s) != 3:
        return
    # deletion
    if s[1] == NULLSHA:
        return
    if s[0] == NULLSHA:
        return s[1]
    else:
        return s[0] + '..' + s[1]

# line is:
# hash type size name
def filterFiles(line, maxsize):
    if len(line) == 0:
        return []
    if line == None:
        return []
    splitted = line.split()
    if splitted[1] != 'blob':
        return []
    # check by mime-type
    cmd = 'git cat-file blob ' + splitted[0]
    cmdfile = ['file', '-b', '--mime-type', '-']
    catfile = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
    out = subprocess.check_output(cmdfile, stdin=catfile.stdout)
    # file may not read the whole file, close the pipe so that git will quit
    catfile.stdout.close()
    catfile.wait()
    outdecoded = out.decode('UTF8')
    # allow text files only (includes sources and html etc.)
    if outdecoded.startswith('text'):
        return []
    # set size limit for the rest
    if int(splitted[2]) > maxsize:
        return [splitted[3]]
    return []

def main():

    files = []

    for line in sys.stdin:
        ref = getRef(line)
        if ref == None:
            continue
        cmd = 'git rev-list --objects ' + ref + ' --not --branches=\* --tags=\*'
        revlist = subprocess.Popen(cmd.split(), stdout=subprocess.PIPE)
        cmd2 = ['git', 'cat-file', '--batch-check=%(objectname) %(objecttype) %(objectsize) %(rest)']
        out = subprocess.check_output(cmd2, stdin=revlist.stdout)
        revlist.wait()
        outdecoded = out.decode('UTF8')
        for o in outdecoded.split('\n'):
            files += filterFiles(o, maxsize)
    if len(files):
        print()
        print('ERROR: binary file(s) detected:')
        for f in files:
            print(f)
        print()
        print('For large (binary) files you are kindly asked to use git lfs.')
        print('Please refer to https://docs.gitlab.com/ee/topics/git/lfs/#using-git-lfs on how to use git lfs.')
        print()
        sys.exit(-1)
    else:
        return

if __name__ == '__main__':
    main()
